config/routes.rb
Globalflush::Application.routes.draw do
  get "home/index"
  get "home/about"
  get "home/graffiti_test"
  get "user_sessions/new"

  match 'map' => 'map#index', :as => :map, :via => :get

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :bathrooms do
    resources :photos
    resources :graffiti do
      resources :photos
    end
  end
  resources :photos
  resources :graffiti do
    resources :photos
  end
  resources :comments
  resources :ratings

  get "users/show"
  match 'users/show' => 'users#show', :as => :user_show

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register

  match 'search' => 'home#search', :as => :search, :via => :get

  root :to => "home#index"

end

app/models/graffiti.rb
#Graffiti is a graffiti that a user might find on the stalls of a bathroom
#Graffit has a one to many relationship with bathroom, e.i. a graffiti can only belong to one bathroom but a bathroom can have many graffiti
#Graffiti have the following attributes:
# - bathroom_id: the id fo the bathroom the graffiti is associated with
# - name: the name of the graffiti
# - description: a simple description of the graffiti
# - moderated: flag for admin and mod usage
# - timestamp: the date of creation and update
class Graffiti < ActiveRecord::Base
  belongs_to :bathroom
  has_many :photos, :as => :imageable, :dependent => :destroy
end

app/controllers/graffiti_controller.rb
# Graffiti Controller
# Handles CRUD of graffiti
class GraffitiController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :update, :edit, :destroy]

  # GET /graffiti/:bathroom_id
  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @graffiti = Graffiti.new
  end

  # POST /graffiti
  def create
    @graffiti = Graffiti.new(params[:graffiti])
    if @graffiti.save
      flash[:notice] = "Graffiti has been added!"
      redirect_to [@graffiti.bathroom,@graffiti]
    else
      render :new
    end
  end

  # GET /graffiti/:bathroom_id
  def index
    if !params[:bathroom_id].nil? then
      @graffiti = Graffiti.where("bathroom_id = ?",params[:bathroom_id])
    else
      @graffiti = Graffiti.find(:all,:order => 'updated_at DESC')
    end
  end

  # GET /graffiti/:id
  def show
    @graffiti = Graffiti.find(params[:id])
  end

  # GET /graffiti/:id
  def edit
    @graffiti = Graffiti.find(params[:id])
  end

  # PUT /graffiti/:id
  def update
    @graffiti = Graffiti.find(params[:id])
    respond_to do |format|
      if @graffiti.update_attributes(params[:graffiti])
        format.html { redirect_to([@graffiti.bathroom,@graffiti], :notice => 'Graffiti was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @graffiti.errors, :status => :unprocessable_entity }
      end
    end

  end
end

app/controllers/graffitis_controller.rb
class GraffitisController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :update, :edit, :destroy]

  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @graffiti = Graffiti.new
  end

  def create
    @graffiti = Graffiti.new(params[:graffiti])
    if @graffiti.save
      flash[:notice] = "Graffiti has been added!"
      redirect_to [@graffiti.bathroom,@graffiti]
    else
      render :new
    end
  end

  def index
      @graffitis = Graffiti.find(:all,:order => 'updated_at DESC')
  end
  
  def show
    @graffiti = Graffiti.find(params[:id])
  end

  def edit
    @graffiti = Graffiti.find(params[:id])
  end

  def update
    @graffiti = Graffiti.find(params[:id])
    respond_to do |format|
      if @graffiti.update_attributes(params[:graffiti])
        format.html { redirect_to([@graffiti.bathroom,@graffiti], :notice => 'Graffiti was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @graffiti.errors, :status => :unprocessable_entity }
      end
    end

  end
end

app/views/graffiti/edit.html.erb
<h1>Editing Graffiti</h1>
<p>This graffiti is in <%= link_to @graffiti.bathroom.title, @graffiti.bathroom %></p>
<%= form_for @graffiti, :url => bathroom_graffiti_url(@graffiti.id),:html => {:multipart => true} do |f| %>
<%= f.error_messages %>
<h3>Basic Information</h3>
<%= f.label :name %><br />
<%= f.text_field :name %><br />
<br/>

<%= f.label :description %><br />
<%= f.text_area :description %><br />

<h3>Photos</h3>
<p>Todo</p>

<%= f.submit "Update" %>

<% end %>

<br />

<%= link_to 'Back to All Graffiti', bathroom_graffiti_path %>

app/views/graffiti/index.html.erb
<h1>Browsing Graffiti</h1>

<p>Currently browsing all graffiti by last added.</p>
<div id="bathroom_list">

<% @graffiti.each do |graffiti| %>
  <div class="list_item">
    <div class="male"><span class="right">Last updated at <%= graffiti.updated_at %></span><%= link_to graffiti.name, bathroom_graffiti_path(graffiti.bathroom,graffiti) %></div>
    <% if graffiti.photos.empty? %>
      <%= link_to image_tag("/images/no_image.png",:height=>80,:width=>120),bathroom_graffiti_path(graffiti.bathroom,graffiti) %>
  <% else %>
    <%= link_to image_tag(graffiti.photos.first.image.url(:thumb),:height=>80,:width=>120),bathroom_graffiti_path(graffiti.bathroom,graffiti) %>
  <% end %>
    <%= graffiti.description %>
  </div>
  <div class="clear"></div>
<% end %>
</div>

app/views/graffiti/new.html.erb
<h1>Adding new Graffiti</h1>

<% form_for [@bathroom,@graffiti] do |f|%>
    <%= f.error_messages %>

    <%= f.hidden_field :bathroom_id, :value => @bathroom.id %>

    <%= f.label "Graffiti Name" %><br />
    <%= f.text_field :name %><br />

    <%= f.label "Description" %><br />
    <%= f.text_field :description %><br />
    <%= f.submit %>
<% end %>

app/views/graffiti/show.html.erb
<script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/javascripts/jquery.jcarousel.min.js"></script>
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('#vcarousel').jcarousel({
      vertical:true,
      scroll:2
    });
    $("#vcarousel li img").click(function(){
      $("#main_image").attr("src",this.src.replace("small","medium"));
      $("#main_link").attr("href",this.src.replace("small","original"));
    }); 
  });
  
</script>

<div id="tools">
  <a href="#">Add to Favorites</a> |
  <a href="#">Share</a> |
  <%= link_to "Edit Photos", [@graffiti.bathroom,@graffiti,:photos] %>  |
  <%= link_to "Edit Content", edit_bathroom_graffiti_path(@graffiti) %>
</div>

<h1><%= @graffiti.name %> </h1>
<% if !@graffiti.photos.empty? then %>
<div id="image_box">
  <%= link_to (image_tag @graffiti.photos.first.image.url(:medium),:id=>"main_image"),@graffiti.photos.first.image.url(:original),:id=>"main_link" %>
  <div class="v-car" style="margin-left:10px;float:right">
    <ul id="vcarousel" class="v-car">
      <% @graffiti.photos.each do |photo| %>
      <li><%= image_tag(photo.image.url(:small)) %></li>
      <% end %>
    </ul>
  </div>
  <div id="add_more"><%= link_to "Add More", new_bathroom_graffiti_photo_path(@graffiti.bathroom,@graffiti) %></div>
</div>
<% else %>
<p>No photos exist for this graffiti. <%= link_to "Add some?", new_bathroom_graffiti_photo_path(@graffiti.bathroom,@graffiti) %></p>
<% end %>
<h2 class="full">Description</h2>
<p><%= @graffiti.description %></p>
<h2 class="full">Location</h2>
<p>Bathroom: <%= link_to @graffiti.bathroom.name, @graffiti.bathroom %></p>
<p>Address: <%= @graffiti.bathroom.address.to_s %></p>