config/routes.rb
Globalflush::Application.routes.draw do
  get "home/index"
  get "home/about"
  get "home/graffiti_test"
  get "user_sessions/new"

  match 'map' => 'map#index', :as => :map, :via => :get

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :bathrooms do
    resources :photos
    resources :graffiti do
      resources :photos
    end
  end
  resources :photos
  resources :graffiti do
    resources :photos
  end
  resources :comments
  resources :ratings

  get "users/show"
  match 'users/show' => 'users#show', :as => :user_show

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register

  match 'search' => 'home#search', :as => :search, :via => :get

  root :to => "home#index"

end

app/models/bathroom.rb
#Bathroom is the place where you go for relief, many places have these and each Bathroom describes the location as well as other information associated with a bathroom
#Bathroom has a one to many relationship with comments, e.i. a bathroom can have many comments.
#Bathroom has a one to many relationship with ratings, e.i. a bathroom cna have many ratings.
#Bathroom has a one to many relationship with graffiti, e.i. a bathroom can have many graffiti.
#Bathroom has a one to one relationship with address, e.i. a bathroom can only have one address.
#Bathroom has a one to many relationship with bathroomSpec, e.i. a bathroom can have many specs.
#Bathroom has a one to many relationship with bathroom_photos, e.i. a bathroom can have many photos.
#Bathroom has a one to many relationship with user, e.i a user can create many bathrooms but a bathroom can only be created by one user.
#Bathroom have the following attributes:
# - title: the name of the bathroom or location name
# - gender: the gender the bathroom is for
# - user_id: id of the user who created the bathroom
# - description: a short summary that described the bathroom
# - hidden: flag for admin and mod usage that hides the bathroom from website
# - moderated: flag for admin and mod usage
# - timestamp: the date of creation and update
# - inside_location: location of the bathroom inside the building

class Bathroom < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :ratings, :dependent => :destroy
  has_many :graffiti, :dependent => :destroy
  has_one :address, :dependent => :destroy
  has_many :bathroom_specs, :dependent => :destroy
  has_many :photos, :as => :imageable, :dependent => :destroy

  belongs_to :user

  accepts_nested_attributes_for :comments, :allow_destroy => true
  accepts_nested_attributes_for :ratings, :allow_destroy => true
  accepts_nested_attributes_for :graffiti, :allow_destroy => true
  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :bathroom_specs, :allow_destroy => true
  accepts_nested_attributes_for :photos, :allow_destroy => true
  

  attr_accessible :comments_attributes, :ratings_attributes, :graffiti_attributes, :address_attributes, :bathroom_specs_attributes, :photos_attributes,
                  :title, :gender, :description, :user_id, :hidden, :moderated, :inside_location


  validates_presence_of :title
  validates_presence_of :gender
  validates_presence_of :description
  validates_presence_of :inside_location


  # Return the title of the bathroom
  def name
    title + " - " + inside_location.to_s + " - " + gender
  end

  # Search function, perform a full text search on the address and ratings
  named_scope :search_by_address, lambda { |keyword, gender, order|
    {
        :joins => :address,
        :include => :ratings,
        :conditions => ['gender LIKE ? AND (inside_location LIKE ? OR street_address LIKE ? OR city LIKE ? OR state LIKE ? OR zip LIKE ? OR country LIKE ? OR title LIKE ?)', "#{gender}", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"],
        :order => order
    }
  }
  
end

app/controllers/bathrooms_controller.rb
# Bathrooms Controller
# It controls all the pages are related to all the CRUD page for bathrooms
# log in is required for CUD, displaying is not required log in
class BathroomsController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :update, :edit, :destroy]
  before_filter :is_admin, :only => :destroy

  # GET /bathrooms/new
  # Bathroom creation page, creates a temporary bathroom object with 1 address, 5 bathroom_specs, and 3 bathroom_photos
  def new
    @bathroom = Bathroom.new
    @bathroom.build_address
    5.times do
      @bathroom.bathroom_specs.build
    end
    3.times do
      @bathroom.photos.build
    end
  end

  # POST /bathrooms
  # Bathroom creation action. Create a bathroom by using data passed from params
  # Return to the bathroom page if it creates successfully
  # Else stays on the 'new' page and indicates the errors
  def create
    @bathroom = Bathroom.new(params[:bathroom])
    @bathroom.build_address(params[:bathroom][:address_attributes])
    if params[:bathroom][:bathroom_specs]
      @bathroom.bathroom_specs.build(params[:bathroom][:bathroom_specs])
    end
    if params[:bathroom][:photos]
      @bathroom.photos.build(params[:bathroom][:photos])
    end

    @bathroom.user_id = @current_user.id
    if @bathroom.save
      flash[:notice] = "Bathroom created!"
      redirect_to bathroom_path(@bathroom.id)
    else
      render :new
    end
  end

  # GET /bathrooms
  # Index page for bathrooms. Query all bathroom and ordered by descending updated_at time
  def index
    @bathrooms = Bathroom.find(:all,:order => 'updated_at DESC')
    @is_admin = is_admin
  end

  # GET /bathrooms/:id
  # Page for showing a single bathroom. 
  def show
    @bathroom = Bathroom.find(params[:id])
  end

  # GET /bathrooms/:id/edit
  # Page for editing a single bathroom.
  def edit
    @bathroom = Bathroom.find(params[:id])
  end

  # PUT /bathrooms/:id
  # Update the bathroom by the params
  # redirect back to the bathroom page if updates successfully
  def update
    @bathroom = Bathroom.find(params[:id])
    respond_to do |format|
      if @bathroom.update_attributes(params[:bathroom]) #&& @bathroom.address.update_attributes(params[:bathroom][:address])
        format.html { redirect_to(@bathroom, :notice => 'Bathroom was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bathroom.errors, :status => :unprocessable_entity }
      end
    end
    
  end

  # DELETE /bathrooms/:id
  # Delete the bathrooms only if the current user is an admin
  # Redirect back to the bathrooms page afterwards
  def destroy
    @bathroom = Bathroom.find(params[:id])
    @bathroom.destroy
    respond_to do |format|
      format.html { redirect_to bathrooms_url }
    end
  end

  
end

app/helpers/bathrooms_helper.rb
# Bathrooms helper module
module BathroomsHelper
end

app/views/bathrooms/_form.html.erb
<%= form_for @bathroom, :url => bathrooms_url, :html => {:multipart => true} do |f| %>
    <%= f.error_messages %>

    <h3>Basic Information</h3>
    <%= f.label :title %><br />
    <% if @bathroom.title.nil? %>
        <%= f.text_field :title %><br />
    <% else %>
        <%= f.label @bathroom.title %><br />
    <% end %>
    <br/>

    <%= f.label :gender %><br />
    <%= select("bathroom", "gender", %w[Male Female], {}, {:include_blank => true}) %><br />
    <br/>

    <%= f.label :description %><br />
    <%= f.text_area :description %><br />

    <h3>Address</h3>
    <%= f.fields_for :address do |a| %>
        <%= a.label :inside_location %><br />
        <%= a.text_field :inside_location %><br />
        <%= a.label :street_address %><br />
        <%= a.text_field :street_address %><br />
        <%= a.label :city %><br />
        <%= a.text_field :city %><br />
        <%= a.label :state %><br />
        <%= a.text_field :state %><br />
        <%= a.label :zip %><br />
        <%= a.text_field :zip %><br />
        <%= a.label :country %><br />
        <%= a.text_field :country %><br />
    <% end %>

    <h3>Details</h3>
    <%= f.fields_for :bathroom_specs do |spec| %>
        <%= spec.text_field :key %>
        <%= spec.text_field :value %>
    <% end %>


    <h3>Photos</h3>
    <%= f.fields_for :photos do |photo| %>
        <%= photo.file_field :image %><br />
    <% end %>

    <br/>



    <%= f.submit "Add" %>
<% end %>

app/views/bathrooms/_map.html.erb
  <!--<meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>-->
  <style type="text/css">
      html {
          height: 100%
      }

      body {
          height: 100%;
          margin: 0px;
          padding: 0px
      }

      #map_canvas {
          height: 100%
      }
  </style>
  <script type="text/javascript"
          src="http://maps.google.com/maps/api/js?sensor=true">
  </script>
  <script type="text/javascript">
      var your_city = new google.maps.LatLng(42.72996, -73.676529);
      var your_place = new google.maps.LatLng(42.72996, -73.676529);
      var marker;
      var map;
      function initialize() {
          var mapOptions = {
              zoom: 15,
              mapTypeId: google.maps.MapTypeId.ROADMAP,
              center: your_city
          };
          map = new google.maps.Map(document.getElementById("map_canvas"),
                  mapOptions);
          marker = new google.maps.Marker({
              map:map,
              draggable:true,
              animation: google.maps.Animation.DROP,
              position: your_place
          });
          google.maps.event.addListener(marker, 'click', toggleBounce);
      }
      function toggleBounce() {
          if (marker.getAnimation() != null) {
              marker.setAnimation(null);
          } else {
              marker.setAnimation(google.maps.Animation.BOUNCE);
          }
      }
  </script>

  
<div id="map" onload="initialize()"></div>

app/views/bathrooms/edit.html.erb
<h1>Editing Bathroom</h1>

<%= form_for @bathroom, :url => bathroom_url(@bathroom.id),:html => {:multipart => true} do |f| %>
    <%= f.error_messages %>

    <h3>Basic Information</h3>
    <div class="left">
    <%= f.label :title %><br />
    <%= f.text_field :title %></div>
    <div class="left">
    <%= f.label :inside_location %><br />
    <%= f.text_field :inside_location %></div>
    <div class="left">
    <%= f.label :gender %><br />
    <%= select("bathroom", "gender", %w[Male Female Unisex], {}, {:include_blank => true}) %><br />
    </div>
    <div class="clear">

    <%= f.label :description %><br />
    <%= f.text_area :description %><br />

    <h3>Address</h3>
    <%= f.fields_for :address do |a| %>
        
        <%= a.label :street_address %><br />
        <%= a.text_field :street_address %><br />
        <%= a.label :city %><br />
        <%= a.text_field :city %><br />
        <%= a.label :state %><br />
        <%= a.text_field :state %><br />
        <%= a.label :zip %><br />
        <%= a.text_field :zip %><br />
        <%= a.label :country %><br />
        <%= a.text_field :country %><br />
    <% end %>

    <h3>Details</h3>
    <table>
    <tr>
        <th>Attribute</th>
        <th>Value</th>
    </tr>
    <%= f.fields_for :bathroom_specs do |spec| %>
      <tr>
        <td><%= spec.text_field :key %></td>
        <td><%= spec.text_field :value %></td>
      </tr>
    <% end %>
    </table>


    <br/>



    <%= f.submit "Update" %>
<% end %>

<br />

<%= link_to 'Back All Bathrooms', bathrooms_path %>

app/views/bathrooms/index.html.erb
<h1>Browsing Bathrooms</h1>

<p>Currently browsing all bathrooms by last added.</p>
<div id="bathroom_list">
<% @bathrooms.each do |bathroom| %>
<div class="list_item">
  <div class="male"><span class="right">Last updated at <%= bathroom.updated_at %></span><%= link_to bathroom.name, bathroom %></div>
  <% if bathroom.photos.empty? %>
    <%= link_to image_tag("/images/no_image.png",:height=>80,:width=>120),bathroom %>
  <% else %>
    <%= link_to image_tag(bathroom.photos.first.image.url(:thumb),:height=>80,:width=>120),bathroom %>
  <% end %>
    <% bathroom.bathroom_specs.each do |spec| %>
    <b><%= spec.key %>:</b> <%=spec.value%>.
    <% end %>

  <% if @is_admin %>
    <%= button_to 'Remove', bathroom_url(bathroom.id), :confirm => 'Are you sure?', :method => :delete  %>
  <% end %>
  
</div>
<div class="clear"></div>
<% end %>
</div>

app/views/bathrooms/new.html.erb
<%=javascript_include_tag :defaults %>
<script type="text/javascript"
        src="http://maps.google.com/maps/api/js?sensor=true">
</script>
<script language="JavaScript" src="http://j.maxmind.com/app/geoip.js"></script>
<script type="text/javascript" language="javascript">
  // variables used by google map and geocoding
  var your_city = new google.maps.LatLng(geoip_latitude(), geoip_longitude()); //central map location, default value is based on ip address
  var marker; //marker location
  var map; //map object
  var geocoder = new google.maps.Geocoder(); //geocoder used for calculating lat/lng and address
  //onload
  google.maps.event.addDomListener(window, "load", initialize);
  
  //initialize map
  function initialize() {
    var mapOptions = {
      zoom: 13,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: your_city
    };
    map = new google.maps.Map(document.getElementById("map_create"),
    mapOptions);
	//initialize marker
	marker = new google.maps.Marker({
	  map:map,
	  draggable:true,
	  animation: google.maps.Animation.DROP,
	  position: your_city
	});
	google.maps.event.addListener(marker, 'dragend', updateAddress);
	geocoder.geocode({'address':geoip_city()+", "+geoip_region_name()}, markMap);
  }
  //use geocoder to get the gps coordinate using address
  function getGPS()
  {
	var address = document.getElementById("street").value+", "
				+document.getElementById("city").value+", "
				+document.getElementById("state").value+", "
				+document.getElementById("zip").value+", "
				+document.getElementById("country").value;
	//alert(address);
	geocoder.geocode({"address":address}, markMap);
  }	
  //mark the map after receiving gps coordinates
  function markMap(results, status)
  {
	if(status == google.maps.GeocoderStatus.OK)
	{
		your_city = results[0].geometry.location;
		map.setCenter(your_city);
		map.setZoom(13);
		marker.setPosition(your_city);
		google.maps.event.addListener(marker, 'dragend', updateAddress);
		//document.getELementById("add").disabled = false;
	}
	else
	{
		alert("Geocode failed because: "+status);
	}
  }
  //update the new marker position before saving to database
  function save_gps()
  {
		your_city = marker.getPosition();
		document.getElementById("lat").value = your_city.lat();
		document.getElementById("long").value = your_city.lng();  
  }
  
  //update the address after user move the marker on the map
  function updateAddress() {
	geocoder.geocode({'latLng':marker.getPosition()}, function(results, status) {
		if (status == google.maps.GeocoderStatus.OK) {
			document.getElementById("street").value = getAddressComponent(results[0], "street_number")+" "+getAddressComponent(results[0], "route");
			document.getElementById("city").value = getAddressComponent(results[0], "locality");
			document.getElementById("state").value = getAddressComponent(results[0], "administrative_area_level_1");
			document.getElementById("zip").value = getAddressComponent(results[0], "postal_code")
			document.getElementById("country").value = getAddressComponent(results[0], "country")
		}
		else {
			alert("Geocoder failed because:" + status);
		}
	});
  }
  //look through the GeocoderResult object to find the correct info for each field in address
  function getAddressComponent(address, type) {
	for (var i=0; i<address.address_components.length; i++) {
		for (var j=0; j<address.address_components[i].types.length; j++) {
			if (address.address_components[i].types[j] == type) {
				return address.address_components[i].long_name;
			}
		}
	}
  }
</script>

<h1>Add New Bathroom</h1>

<%= form_for @bathroom, :url => bathrooms_url,:html => {:multipart => true} do |f| %>
    <%= f.error_messages %>

    <h3>Basic Information</h3>
    <div class="left">
    <%= f.label :title %><br />
    <%= f.text_field :title %></div>
    <div class="left">
    <%= f.label :inside_location %><br />
    <%= f.text_field :inside_location %></div>
    <div class="left">
    <%= f.label :gender %><br />
    <%= select("bathroom", "gender", %w[Male Female Unisex], {}, {:include_blank => true}) %><br />
    </div>
    <div class="clear">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
    </div>

    <h3>Address</h3>
    <div id="mapbox_create">
      <div id="map_create">
      </div>
    </div>
    <div id="create_address">
    <%= f.fields_for :address do |a| %>       
        <%= a.label :street_address %><br />
        <%= a.text_field :street_address, :id => "street" %><br />
        <%= a.label :city %><br />
        <%= a.text_field :city, :id => "city" %><br />
        <%= a.label :state %><br />
        <%= a.text_field :state, :id => "state" %><br />
        <%= a.label :zip %><br />
        <%= a.text_field :zip, :id => "zip" %><br />
        <%= a.label :country %><br />
        <%= a.text_field :country, :id => "country" %><br />
		<%= a.hidden_field :latitude, :id => "lat" %><br />
		<%= a.hidden_field :longitude, :id => "long" %><br />
    <% end %>
    <button type="button" onclick="getGPS(this)">Check Address</button>
    </div>
    <div style="clear:both"></div>
    <h3>Details</h3>
    <table>
    <tr>
        <th>Attribute</th>
        <th>Value</th>
    </tr>
    <%= f.fields_for :bathroom_specs do |spec| %>
      <tr>
        <td><%= spec.text_field :key %></td>
        <td><%= spec.text_field :value %></td>
      </tr>
    <% end %>
    </table>

    <h3>Photos</h3>
    <h4>You can upload photos now or after you create the bathroom.</h4>
    <%= f.fields_for :photos do |photo| %>
        <%= photo.file_field :image %><br />
    <% end %>

    <br/>



    <%= f.submit "Add", :onclick =>"save_gps()"%>
<% end %>

<br />

<%= link_to 'Back All Bathrooms', bathrooms_path %>

app/views/bathrooms/show.html.erb
<%=javascript_include_tag :defaults %>
<script type="text/javascript"
        src="http://maps.google.com/maps/api/js?sensor=true">
</script>
<script type="text/javascript" language="javascript">
  var your_city = new google.maps.LatLng(<%= @bathroom.address.latitude %>, <%= @bathroom.address.longitude %>);
  var your_place = new google.maps.LatLng(<%= @bathroom.address.latitude %>, <%= @bathroom.address.longitude %>);
  var marker;
  var map;
  google.maps.event.addDomListener(window, "load", initialize);
  function initialize() {
    var mapOptions = {
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: your_city
    };
    map = new google.maps.Map(document.getElementById("map"),
    mapOptions);
    marker = new google.maps.Marker({
      map:map,
      draggable:true,
      animation: google.maps.Animation.DROP,
      position: your_place
    });
    google.maps.event.addListener(marker, 'click', toggleBounce);
  }
  function toggleBounce() {
    if (marker.getAnimation() != null) {
      marker.setAnimation(null);
    } else {
      marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  }
</script>

<script type="text/javascript" language="javascript">

  var oMax;	// Isthe maximum number of stars
  var cMax;
  var sMax;
  //var holder; // Is the holding pattern for clicked state
  var preSet_overall; // Is the PreSet value onces a selection has been made
  var preSet_clean;
  var preSet_smell;
  var overall_rated = 0;
  var smell_rated = 0;
  var clean_rated = 0;


  // Rollover for image Stars //
  function rating(num){
    sMax = 5;	// Isthe maximum number of stars
    cMax = 5;
    oMax = 5;

    if(!overall_rated && num.id[0]=='0'){
      
      s = num.id[1]; // Get the selected star
      for(i=1; i<=oMax; i++){
        if(i<=s){
          document.getElementById("0"+i).className = "onstar";
        }else{
          //document.getElementById("0"+i).className = "offstar";
        }
      }

    }
    if(!clean_rated && num.id[0]=='1'){
      s = num.id[1]; // Get the selected star
      for(i=1; i<=cMax; i++){
        if(i<=s){
          document.getElementById("1"+i).className = "onstar";
        }else{
          //document.getElementById("1"+i).className = "offstar";
        }
      }
    }
    if(!smell_rated && num.id[0]=='2'){
      s = num.id[1]; // Get the selected star
      for(i=1; i<=sMax; i++){
        if(i<=s){
          document.getElementById("2"+i).className = "onstar";
        }else{
          //document.getElementById("2"+i).className = "offstar";
        }
      }
    }
  }

  // For when you roll out of the the whole thing //
  function off(me){
    if(!overall_rated && me.id[0]=='0'){
      if(!preSet_overall){
        for(i=1; i<=oMax; i++){
          document.getElementById("0"+i).className = "offstar";
        }
      }else{
        rating(preSet_overall);
      }
    }
    if(!clean_rated && me.id[0]=='1'){
      if(!preSet_clean){
        for(i=1; i<=cMax; i++){
          document.getElementById("1"+i).className = "offstar";
        }
      }else{
        rating(preSet_clean);
      }
    }
  if(!smell_rated && me.id[0]=='2'){
    if(!preSet_smell){
      for(i=1; i<=sMax; i++){
        document.getElementById("2"+i).className = "offstar";
      }
    }else{
      rating(preSet_smell);
    }
  }
}

// When you actually rate something //
function rate(me){
  if(me.id[0] == 0){
    preSet_overall = me;
    overall_rated = 1;
  }else if(me.id[0] == 1){
    preSet_clean = me;
    clean_rated = 1;
  }else{
    preSet_smell = me;
    smell_rated = 1;
  }
  sendRate(me);
  rating(me);
}

// Send the rating information somewhere using Ajax or something like that.
function sendRate(sel){
  //alert("Your rating was: "+sel.id[1]);
}
  
function show_rating(score){
  if (score > 0){
    r = 0;
    for (i=1; i<score; i++){
      document.getElementById("_"+i).className = "onstar";
      r = i;
    }
    document.getElementById("_"+r).className = "s"+Math.round((score - r) * 10);
  }
}
	
function update_hidden(){
  document.comment_rating.overall.value = preSet_overall.id[1];
  document.comment_rating.clean.value = preSet_clean.id[1];
  document.comment_rating.smell.value = preSet_smell.id[1];
}
</script>
<!--  BOT -->

<div id="tools">
  Add to Favorites | Check In | Share |
  <%= link_to "Edit Photos", bathroom_photos_path(@bathroom.id) %>|
  <%= link_to "Edit Content", edit_bathroom_path(@bathroom.id) %>
</div>

<div id="big_stars">
  <% s = @bathroom.ratings.collect { |c| c.overall} %>
  <% stars = (s.size == 0 ? 0 : s.sum.to_f / s.size.to_f)*10 %>
  <% tstars = 0 %>
  <% while stars > 10 %>
    <%= image_tag("/images/stars/10.png") %>
    <% stars -= 10 %>
    <% tstars += 1 %>
  <% end %>
  <%= image_tag("/images/stars/" + stars.floor.to_s + ".png") %>
  <% while tstars < 4 %>
    <%= image_tag("/images/stars/0.png") %>
    <% tstars += 1 %>
  <% end %>
</div>
<h1><%= @bathroom.name %> -
  <% if @bathroom.gender == "Male" %>
    &#9794;
  <% elsif @bathroom.gender == "Female" %>
    &#9792;
  <% end %>
</h1>

<div id="right_column">
  <h3>Photos</h3>
  <% @bathroom.photos.limit(2).each do |photo| %>
    <div><a href="<%= photo.image.url %>"><%= image_tag photo.image.url(:small),:height=>133,:width=>200 %></a></div>
  <% end %>
  <%  if @bathroom.photos.size > 2 then %>
    <%= link_to 'View All (' + @bathroom.photos.size.to_s + ')', bathroom_photos_path(@bathroom) %> |
  <% end %>
  <%= link_to 'Add Photo', new_bathroom_photo_path(@bathroom) %>
    <h3>Graffiti</h3>
  <% if !@bathroom.graffiti.empty? then %>

      <% @bathroom.graffiti.limit(2).each do |graffiti| %>
        <% if graffiti.photos.empty? then %>
          <div><%= link_to image_tag("/images/no_image.png",:width=>200,:height=>133),[@bathroom,graffiti] %></div>
        <% else %>
          <div><%= link_to image_tag(graffiti.photos.first.image.url(:small),:width=>200,:height=>133),[@bathroom,graffiti] %></div>
        <% end %>
      <% end %>
    <%  if @bathroom.graffiti.size > 2 then %>
      <%= link_to 'View All (' + @bathroom.graffiti.size.to_s + ')',bathroom_graffiti_index_path(@bathroom) %> |
    <% end %>
  <% end %>
  <%=  link_to 'Add Graffiti',new_bathroom_graffiti_path(@bathroom) %>
</div>

<div id="left_main">

<div id="top_block">

<div id="left_column">
  <div id="mapbox">
    <div id="map">
    </div>
  </div>
</div>

<h2>Location</h2>
<p><%= @bathroom.address.to_s %></p>

<h2>Description</h2>
<p><%= @bathroom.description %></p>

<h2>Attributes</h2>
<div id="attribute_box">
  <div id="ab_left">
    <ul>
      <% @bathroom.bathroom_specs.each do |spec| %>
        <li><%= spec.key %></li>
      <% end %>
    </ul>
  </div>
  <div id="ab_right">
    <ul>
      <% @bathroom.bathroom_specs.each do |spec| %>
        <li><%= spec.value %></li>
      <% end %>
    </ul>
  </div>
</div>
</div>

<h2>Write a Review</h2>
<div id="add_comment" >
<%= form_for :comment, :url => comments_path , :html => {:name => "comment_rating"} do |f| %>
  <%= f.error_messages %>
  <%= f.text_area :body,:style => "float:left" %>
  <%= f.hidden_field :bathroom_id, :value => @bathroom.id %>
  <br />
  <%= f.hidden_field :overall, :id => "overall" %>
  <%= f.hidden_field :clean, :id => "clean" %>
  <%= f.hidden_field :smell, :id => "smell"%>

<div id="rating_box" style="float:left">
    <div id="rb_left">
      <ul>
        <li>Overall Rating</li>
        <li>Cleanliness</li>
        <li>Smelliness</li>
      </ul>
    </div>
    <div id="rb_right">
      <ul>
        <li>
          <div class="offstar" onclick="rate(this)" id="01" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="02" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="03" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="04" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="05" onmouseover="rating(this)" onmouseout="off(this)"></div>
        </li>
        <li>
          <div class="offstar" onclick="rate(this)" id="11" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="12" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="13" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="14" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="15" onmouseover="rating(this)" onmouseout="off(this)"></div>
        </li>
        <li>
          <div class="offstar" onclick="rate(this)" id="21" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="22" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="23" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="24" onmouseover="rating(this)" onmouseout="off(this)"></div>
          <div class="offstar" onclick="rate(this)" id="25" onmouseover="rating(this)" onmouseout="off(this)"></div>
        </li>
      </ul>
    </div>
  </div>
  <div style="clear:both"></div>
  <div id="submit_container" style="text-align:center">
    <%= f.submit "Post Comment" , :onclick => "update_hidden()", :style => "clear:both" %>
  </div>
<% end %>
</div>
<h2 class="">Reviews</h2>
<% @bathroom.comments.each do |comment| %>
  <div class="review">
    <div class="username"><%= link_to comment.user.login, comment.user %></div>
    <div class="date_posted"><%= comment.created_at.strftime("%I:%M%p %m/%d/%Y") %></div>
    <p><%= comment.body %></p>
  </div>
<% end %>
</div>