config/routes.rb
Globalflush::Application.routes.draw do
  get "home/index"
  get "home/about"
  get "home/graffiti_test"
  get "user_sessions/new"

  match 'map' => 'map#index', :as => :map, :via => :get

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :bathrooms do
    resources :photos
    resources :graffiti do
      resources :photos
    end
  end
  resources :photos
  resources :graffiti do
    resources :photos
  end
  resources :comments
  resources :ratings

  get "users/show"
  match 'users/show' => 'users#show', :as => :user_show

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register

  match 'search' => 'home#search', :as => :search, :via => :get

  root :to => "home#index"

end

app/controllers/home_controller.rb
# Home controller
# It contains the root of this application, the homepage
# And a static link 'about' page of the application
class HomeController < ApplicationController

  # GET /
  # Root of this application, the index page
  def index
    @bathrooms = Bathroom.all(:limit=>9,:order => 'updated_at DESC')
    @graffiti = Graffiti.all(:limit=>9,:order => 'updated_at DESC')
  end

  # GET /home/about
  # This is the about page
  def about
  end

  # for testing purpose: the graffiti page
  def graffiti_test
  end

  # GET /search
  # Search for bathroom by keywords
  # Calling named_scope in Bathroom model
  def search
    @is_admin = is_admin

    gender = '%'
    if params[:male] == '1' && params[:female] != '1'
        gender = 'Male'
    end
    if params[:male] != '1' && params[:female] == '1'
      gender = 'Female'
    end
	if params[:male] == '1' && params[:female] == '1'
	 gender = '%'
	end
	
    sort_order = params[:sort] || "bathrooms.updated_at DESC"

    @bathrooms = Bathroom.search_by_address(params[:keyword], gender, sort_order)
    
    @addresses = @bathrooms.map { |b| b.address }
    @ratings = @bathrooms.map { |b| b.ratings }

    @bathrooms_with_address_ratings = @bathrooms.map { |b| [b, b.address, b.ratings] }

    
    respond_to do |format|
      format.html { render }
      format.xml  { render :xml => @bathrooms_with_address_ratings }
      format.json { render :json => @bathrooms_with_address_ratings }
    end
    
  end
  
end

app/helpers/home_helper.rb
# Home helper module
module HomeHelper
end

app/views/home/about.html.erb
<h1>About Us</h1>

<iframe src="https://docs.google.com/document/pub?id=1JKpupfztVN_N_JYoCRP_qCwZbDqoYJrCuwWQJjispGs&amp;embedded=true" width="100%" height="100%"></iframe>

app/views/home/graffiti_test.html.erb
<script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/javascripts/jquery.jcarousel.min.js"></script>
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('#vcarousel').jcarousel({
      vertical:true,
      scroll:2
    });
  });
</script>

<div id="tools">
  <a href="#">Add to Favorites</a> |
  <a href="#">Share</a> |
  <a href="#">Edit Photos</a> |
  <a href="#">Edit Content</a>
</div>

<h1>Jinzhen's Game Face</h1>
<div id="image_box">
  <img id="main_image" src="http://photos.cuttlefishtech.com/last-lan-5-16/1200.800.90.IMG_4170.JPG"/>
  <div class="v-car" style="float:right">
    <ul id="vcarousel" class="v-car">
      <li><img src="http://photos.cuttlefishtech.com/last-lan-5-16/200.133.90.IMG_4170.JPG"/></li>
      <li><img src="http://photos.cuttlefishtech.com/last-lan-5-16/200.133.90.IMG_4196.JPG"/></li>
      <li><img src="http://photos.cuttlefishtech.com/last-lan-5-16/200.133.90.IMG_4198.JPG"/></li>
      <li><img src="http://photos.cuttlefishtech.com/last-lan-5-16/200.133.90.IMG_4275.JPG"/></li>
      <li><img src="http://photos.cuttlefishtech.com/last-lan-5-16/200.133.90.IMG_4090.JPG"/></li>
    </ul>
  </div>
  <div id="add_more">Add More</div>
</div>
<h2 class="full">Description</h2>
<p>This graffiti showcases the complex techniques used to create scratch-art.
  It's not clear exactly what sort of tool, be it a knife or a razor blade,
  was used to create this result, but it sure is wonderful.</p>
<h2 class="full">Comments?</h2>
<p>Do we want to have comments on graffiti?</p>

app/views/home/index.html.erb
<script type="text/javascript" src="/javascripts/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/javascripts/jquery.jcarousel.min.js"></script>
<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('#carousel').jcarousel();
    jQuery('#g_car').jcarousel();
  });
  function clickclear(thisfield, defaulttext) {
    if (thisfield.value == defaulttext) {
      thisfield.value = "";
    }
  }
  function clickrecall(thisfield, defaulttext) {
    if (thisfield.value == "") {
      thisfield.value = defaulttext;
    }
  }
</script>
<h1>Welcome to Global Flush</h1>
<p>Global Flush is a fun and exciting way to find the best (and worst) bathrooms.</p>
<p>Get started by searching a geographical area or browsing the top rated facilties.</p>
<h3>Find a Bathroom</h3>
<div id="find">

  <% form_tag search_url, :method => 'get' do %>
      <%= text_field_tag :keyword, params[:keyword], :id=> "zip_home" %>
      <%= submit_tag "Search", :name => nil, :id=>"search" %>
  <% end %>
  
  <div class="home_button" id="via_map"><%= link_to 'via Map', '/map' %></div>
  <div class="home_button" id="via_browse"><%= link_to 'via Browse', bathrooms_url%></div>
</div>
<h3>Newest Bathrooms</h3>
<div class="h-car">
  <ul id="carousel" class="h-car">
    <% @bathrooms.each do |bathroom| %>
      <li>
        <% if bathroom.photos.empty? == false %>
          <%= link_to image_tag(bathroom.photos.first.image.url(:small)), bathroom %>
        <% else %>
          <%= link_to image_tag("/images/no_image.png",:width=>240,:height=>160), bathroom %>
        <% end %>
        <div><%= link_to bathroom.name,bathroom %></div>
      </li>
    <% end %>
  </ul>
</div>
<h3>Newest Graffiti</h3>
<div class="h-car">
  <ul id="g_car" class="h-car">
    <% @graffiti.each do |graffiti| %>
      <li>
        <% if graffiti.photos.empty? == false %>
          <%= link_to image_tag(graffiti.photos.first.image.url(:small)), bathroom_graffiti_path(graffiti.bathroom,graffiti) %>
        <% else %>
          <%= link_to image_tag("/images/no_image.png",:width=>240,:height=>160), bathroom_graffiti_path(graffiti.bathroom,graffiti) %>
        <% end %>
        <div><%= link_to graffiti.name,bathroom_graffiti_path(graffiti.bathroom,graffiti) %></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/index.html.haml
<h1>HOME#INDEX</h1>
<p>Find me in app/views/home/index.html.haml</p>
<h1>THIS WILL BE THE HOMEPAGE!</h1>
#user_nav
- if current_user
  = "Signed in as "
  = link_to current_user.email, user_show_path
  = ". Not you?"
  = link_to "Sign out", logout_path
- else
  = link_to "Sign in", login_path

  

app/views/home/index2.html.haml
<h1>HOME#INDEX</h1>
<p>Find me in app/views/home/index.html.haml</p>
<h1>THIS WILL BE THE HOMEPAGE!</h1>
#user_nav
- if current_user
  = "Signed in as "
  = link_to current_user.email, user_show_path
  = ". Not you?"
  = link_to "Sign out", logout_path
- else
  = link_to "Sign in", login_path

  

app/views/home/search.html.erb
<h1>Search Bathrooms</h1>

<%#= params.inspect %>
<% current_keyword = params[:keyword] %>

<div id="search_form">
  <%# form_tag search_url, :method => 'get' do %>
      <%#= text_field_tag :keyword, params[:keyword], :value => current_keyword %>
      <%#= submit_tag "Search", :name => nil %>
  <%# end %>
</div>

    <div id="filter">

      <% form_tag search_url, :method => :get do %>

          <%= text_field_tag :keyword, params[:keyword], :value => current_keyword %><br/>

          Show:
          <%= check_box_tag :male, 1, params[:male] == '1' %>Male
          <%= check_box_tag :female, 1, params[:female] == '1' %>Female<br />

          Sort by: <br />
          Updated at:
          <%= radio_button_tag :sort, 'bathrooms.updated_at DESC', params[:sort] == 'bathrooms.updated_at DESC' %>Most recent
          <%= radio_button_tag :sort, 'bathrooms.updated_at ASC', params[:sort] == 'bathrooms.updated_at ASC' %>Oldest
          <br/>
          
          Ratings:
          <%= radio_button_tag :sort, 'ratings.overall DESC', params[:sort] == 'ratings.overall DESC' %>High to low
          <%= radio_button_tag :sort, 'ratings.overall ASC', params[:sort] == 'ratings.overall ACS' %>Low to high
          <br/>

          <!--Distance:-->
          <%#= radio_button_tag :sort,  'distance DESC', params[:sort] == 'distance DESC'%>
          <!--Furthest to closest-->
          <%#= radio_button_tag :sort,  'distance ASC', params[:sort] == 'distance ACS' %>
          <!--Closest to furthest-->
          <br/>

          <%= submit_tag "Search", :name => nil %>
      <% end %>

    </div>

<% if @bathrooms.empty? %>
    <p>There are no such matching bathrooms. Please try again.</p>
<% else %>



    <div id="bathroom_list">

      <% @bathrooms.each do |bathroom| %>
          <div class="list_item">
            <div class="male">
              <span class="right">Last updated at <%= bathroom.updated_at %></span><%= link_to bathroom.name, bathroom %>
            </div>
            <% if bathroom.photos.empty? %>
                <%= link_to image_tag("/images/no_image.png", :height=>80, :width=>120), bathroom %>
            <% else %>
                <%= link_to image_tag(bathroom.photos.first.image.url(:thumb), :height=>80, :width=>120), bathroom %>
            <% end %>
            <% bathroom.bathroom_specs.each do |spec| %>
                <b><%= spec.key %>:</b> <%= spec.value %>.
            <% end %>

            <% if @is_admin %>
                <%= button_to 'Remove', bathroom_url(bathroom.id), :confirm => 'Are you sure?', :method => :delete  %>
            <% end %>
          </div>

          <div class="clear"></div>
      <% end %>
    </div>

<% end %>