config/routes.rb
Globalflush::Application.routes.draw do
  get "home/index"
  get "home/about"
  get "home/graffiti_test"
  get "user_sessions/new"

  match 'map' => 'map#index', :as => :map, :via => :get

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :bathrooms do
    resources :photos
    resources :graffiti do
      resources :photos
    end
  end
  resources :photos
  resources :graffiti do
    resources :photos
  end
  resources :comments
  resources :ratings

  get "users/show"
  match 'users/show' => 'users#show', :as => :user_show

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register

  match 'search' => 'home#search', :as => :search, :via => :get

  root :to => "home#index"

end

app/views/layouts/_footer.html.erb
<div id="byline">All Rights Reserved - Copyright &copy; Global Flush 2011</div>

<div id="footer_shadow"></div>

app/views/layouts/_header.html.erb
<div id="header">
  <img src="/images/logo.png" alt="Global Flush Logo"/>

  <div id="login">
    <!-- <a href="#">Login</a> | <a href="#">Register</a> -->
    <% if current_user %>
        Signed in as <%= link_to current_user.email, user_show_path %> | <%= link_to 'Logout', logout_path %>
    <% else %>
        <%= link_to 'Sign in', login_path %> | <%= link_to 'Register', register_path %>
    <% end %>
  </div>

  <div id="switcher">
    <strong>
      <%= link_to 'Male', :controller => 'home', :action => 'search', :male => 1 %>
    </strong>
    | 
    <%= link_to 'Female', :controller => 'home', :action => 'search', :female => 1 %>
    |
    <%= link_to 'Graffiti',graffiti_index_path %></div>
</div>

app/views/layouts/_navigation.html.erb
<div id="nav">
  <div id="bar">
    <%= link_to 'Home', root_url %>
    <%= link_to 'Browse', bathrooms_url %>
    <%= link_to 'Search', search_url %>
    <%= link_to 'Map', map_url %>
    <%= link_to 'Add', new_bathroom_url %>
    <a href="#">Top</a>
    <div>
      <%= link_to 'About', home_about_url  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Globalflush</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/globalflush.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN">
<html>

<!-- <link rel="stylesheet" type="text/css" href="stylesheets/globalflush.css"> -->

<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>

<title>Global Flush</title>
<head>

</head>
<body>
  <%= render :partial => "layouts/header" %>
  <%= render :partial => "layouts/navigation" %>
  <div id="content">
    <%= flash[:notice] %>

    <%= yield %>

  </div>
</body>
<%= render :partial => "layouts/footer" %>

</html>